# Generated by Django 4.2.5 on 2023-09-21 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meme',
            name='isFunny',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meme',
            name='title',
            field=models.CharField(default='title', max_length=25),
            preserve_default=False,
        ),
    ]
