# Generated by Django 4.2.5 on 2023-09-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_meme_description_meme_isfunny_meme_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='description',
            field=models.TextField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='meme',
            name='isFunny',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(default='', max_length=25),
        ),
    ]
